export enum Roles {
  ADMIN = 'ADMIN',
  REGION_HEAD = 'REGION_HEAD',
  BRANCH_HEAD = 'BRANCH_HEAD',
  FRANCHISE_HEAD = 'FRANCHISE_HEAD',
  MANAGER = 'MANAGER',
  OPERATOR = 'OPERATOR',
  QUALITY_INSPECTOR = 'QUALITY_INSPECTOR',
  SAFETY_OFFICER = 'SAFETY_OFFICER',
  EMPLOYEE = 'EMPLOYEE',
}

export default Roles;
